name: Scheduled Pull

on:
  schedule:
    - cron: "*/1 * * * *"     

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: simplecontainer

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Pull Image
        run: |
          IMAGE_ID=containers.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          docker pull $IMAGE_ID:$VERSION 
